import { api } from '../lib/api'

export const getPayrolls      = () => api.get('/hr/payrolls').then(r => r.data)
export const getPayroll       = (id: string) => api.get(`/hr/payrolls/${id}`).then(r => r.data)
export const getPayrollDetail = (id: string) => api.get(`/hr/payrolls/${id}/detail`).then(r => r.data)
export const getPayslip       = (lineId: string) => api.get(`/hr/payslip/${lineId}`).then(r => r.data)
export const createPayrollMonth = (month: number, year: number) => api.post('/hr/payrolls/create-month', { month, year }).then(r => r.data)
export const validatePayrollLine = (id: string) => api.patch(`/hr/payroll-lines/${id}/validate`).then(r => r.data)
export const payPayrollLine = (id: string, data: { treasuryAccountId: string; paymentMethod?: string; reference?: string }) => api.patch(`/hr/payroll-lines/${id}/pay`, data).then(r => r.data)
export const deletePayroll    = (id: string) => api.post(`/hr/payrolls/${id}/delete`).then(r => r.data)
export const updatePayrollLine = (id: string, d: any) => api.patch(`/hr/payroll-lines/${id}`, d).then(r => r.data)
export const toggleBlockPayrollLine = (id: string, blocked: boolean, reason?: string) => api.patch(`/hr/payroll-lines/${id}/block`, { blocked, reason }).then(r => r.data)
export const getLeaves        = (p?: any) => api.get('/hr/leaves', { params: p }).then(r => r.data)
export const createLeave      = (d: any) => api.post('/hr/leaves', d).then(r => r.data)
export const approveLeave     = (id: string) => api.patch(`/hr/leaves/${id}/approve`).then(r => r.data)
export const rejectLeave      = (id: string, reason: string) => api.patch(`/hr/leaves/${id}/reject`, { reason }).then(r => r.data)
export const getTrainings     = () => api.get('/hr/trainings').then(r => r.data)
export const createTraining   = (d: any) => api.post('/hr/trainings', d).then(r => r.data)
export const getDisciplinary  = (agentId?: string) => api.get('/hr/disciplinary', { params: agentId ? { agentId } : {} }).then(r => r.data)
export const createDisciplinary = (d: any) => api.post('/hr/disciplinary', d).then(r => r.data)

export const getCandidacies         = (p?: any) => api.get('/hr/candidacies', { params: p }).then(r => r.data)
export const createCandidacy        = (d: any) => api.post('/hr/candidacies', d).then(r => r.data)
export const updateIntegrationStep  = (id: string, d: any) => api.patch(`/hr/integration-steps/${id}`, d).then(r => r.data)
export const convertCandidacyToAgent = (id: string, d: any) => api.post(`/hr/candidacies/${id}/convert-to-agent`, d).then(r => r.data)
export const getContractExpiryAlerts = (days?: number) => api.get('/hr/alerts/contract-expiry', { params: days ? { days } : {} }).then(r => r.data)
export const getIndisciplinedAgents  = () => api.get('/hr/alerts/indisciplined').then(r => r.data)
export const getHrStats              = () => api.get('/hr/stats').then(r => r.data)
export const getContracts            = (p?: { status?: string; contractType?: string }) => api.get('/hr/contracts', { params: p }).then(r => r.data)
